name: yxy
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
  - pytorch
  - numba/label/dev
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - soumith
  - hargup/label/pypi
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - python=3.6
  - cudatoolkit
  - tensorflow-gpu=1.14.0
  - tensorboard=1.14.0
  - tqdm
  - opencv
  - matplotlib
  - pillow
  - requests
  - pathlib
  - scipy
  - numpy
  - scikit-learn
  - hashlib
  - six
